### ISSUE TITLE
Notice style for containers

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#139]
I have found this nice effect on this [GPL licensed theme](http://mademistakes.com/articles/minimal-mistakes-jekyll-theme/)

![screen shot 2014-06-01 at 7 03 32 pm](https://cloud.githubusercontent.com/assets/715377/3142179/c5f37b70-e9ae-11e3-8d26-df6c79fd81fa.png)

Which you can use in your Silex site

![screen shot 2014-06-01 at 6 57 01 pm](https://cloud.githubusercontent.com/assets/715377/3142165/edcc50e6-e9ad-11e3-8608-a75aeaf18021.png)

It is a simple CSS rule to paste anywhere in the CSS editor:

``` css
.notice:before {
    position: absolute;
    top: -20px;
    left: 0;
    width: 0;
    height: 0;
    border-color: transparent #7f8c8d #7f8c8d transparent;
    border-style: solid;
    border-width: 10px;
    content: "";
}
```

And then you can just add the `notice` CSS class to elements (Apollo mode, bottom right text field "CSS classes") like this:

![screen shot 2014-06-01 at 7 02 02 pm](https://cloud.githubusercontent.com/assets/715377/3142177/8a2d050c-e9ae-11e3-859b-c375821b3bee.png)
