### ISSUE TITLE
Upload Assets / Image failed

### ISSUE THREAD

**Issue by mrfzy00** [silexlabs/Silex#1627]
Hello,

I use Silex by looking from AlternativeTo.net. I just saw and try by deploying it using the Docker. But after I try to deploy, there some errors found while I try to upload some images. The error code said:

> Error uploading assets TypeError [ERR_INVALID_URL]: Invalid URL silex-web-1     |     at new NodeError (node:internal/errors:405:5)

Is it any configuration related to the Docker Compose that would shown an error?

Kindly for your reply

Specification:
- Ubuntu 22.04 Jammy LTS
- Docker v28.0.0

**Comment by lexoyo** [comment]
Hello
I'll try on my side but I've never seen this error
You don't have more in the error?

**Comment by TomErnst1972** [comment]
i tried the same. Firing up a simple docker container generates multiple errors. Let's see:

my docker-compose.yaml:
```
services:
    silex:
        container_name: silex
        ports:
            - 6805:6805
        volumes:
            - $PWD/storage:/silex/silex/storage
            - $PWD/hosting:/silex/silex/hosting
        image: silexlabs/silex
```
first error directly calling the webpage:
```
An error occured.
ENOENT: no such file or directory, open '/silex/silex/storage/default/website.json'
```

than, trying to add e.g. a picture brings an error:
```
An error occured.
ENOENT: no such file or directory, open '/silex/silex/storage/default/assets/Comic1.jpeg'
```
and indeed, the mentioned folders are missing in the mapped folders.
 Screenshot:

![Image](https://github.com/user-attachments/assets/f5997e3f-3733-4039-86d2-a6632f4f861b)

this continues to happen with other elements as well, i gave up after manually creating one of the missing folders.
(assets, css, etc.)
