### ISSUE TITLE
Accordion widget for Silex

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#208]
This is a widget to transform a container into a very nice interactive accordion.

![accordion](https://cloud.githubusercontent.com/assets/715377/4516535/3a07f2d4-4bfc-11e4-9c2f-243a81c0ca09.png)

It is based on [Nate Armagost zaccordion Jquery plugin](http://www.armagost.com/zaccordion).
## Install the widget in your website

Download the zip file [jquery.zaccordion.zip](http://www.armagost.com/wp-content/plugins/download-monitor/download.php?id=7) and unzip it somewhere. Then copy the file `/js/jquery.zaccordion.min.js` to your dropbox, **in the same folder as your website**.

Open your website in [Silex](http://editor.silex.me), and open the javascript editor (view menu) to paste this code anywhere there

``` javascript
 /************************************************\
|  Accordion plugin                                |
|  Based on http://www.armagost.com/zaccordion/    |
 \************************************************/
document.write('<scr'+'ipt type="text/notjavascript" src="./jquery.zaccordion.min.js"></scr'+'ipt>');
$(function(){
    $(".accordion").each(function(){
        $(this).zAccordion({
            timeout: 4000,
            slideWidth: Math.round($(this).width() * .75),
            width: Math.round($(this).width()),
            height: Math.round($(this).height())
        });
        // let Silex handle the style.display property (used by the pageable plugin)
        $(this).css('display', '');
    });
});
```

This should look like this:

![screen shot 2014-10-04 at 9 43 55 pm](https://cloud.githubusercontent.com/assets/715377/4516579/eae73946-4bfe-11e4-9b29-a7146a37001c.png)

Then open the CSS editor (view menu) and paste this code anywhere 

``` css
 /************************************************\
|  Accordion plugin                                |
|  Based on http://www.armagost.com/zaccordion/    |
 \************************************************/
/* style of the cells */
.accordion > .editable-style {
    box-shadow: -6px 0 10px -4px rgba(0,0,0,0.5);
}
/* style when editing in Silex */
body.editable-plugin-created .accordion{
    overflow-y: auto;
}
body.editable-plugin-created .accordion > .editable-style {
    height: 100% !important;
    width: 75% !important;
    top: auto !important;
    left: auto !important;
    top: initial !important;
    left: initial !important;
    position: relative !important;
    padding: 0px !important;
}
```
## Add an accordion widget to your website

Enter the advanced Apollo mode of Silex (Tools menu). Create an empty container (Insert menu). And then give it the `accordion` CSS class (use the CSS classes text field from the element's properties)

![Set the CSS class](https://cloud.githubusercontent.com/assets/715377/4516603/614b8262-4c00-11e4-9875-ced7d97d212e.png)

From now on, you can drop containers into the accordion, and they will add up vertically, with the perfect size. Working with the elements in the accordion will look like this:

![working with the elements in the accordion](https://cloud.githubusercontent.com/assets/715377/4516610/c6ebc1e0-4c00-11e4-989c-9b8be2223e42.png)

To see the real accordion, you need to save your website and preview it (View menu). This will look like this:

![The real look of the accordion](https://cloud.githubusercontent.com/assets/715377/4516628/2c2c2022-4c01-11e4-823e-8cc72f4ea5c2.png)
