### ISSUE TITLE
Animations: page transitions

### ISSUE THREAD

**Issue by singchan** [silexlabs/Silex#445]
This is how to make transitions between pages smooth, with an opacity fade-in and fade-out. 

In the CSS editor (`view` menu, `CSS styles editor`), add this code somewhere:

``` CSS
.loaded .paged-element-visible {
    transition: opacity .5s;
}
.loaded .paged-element.paged-element-hidden {
    display: inherit;
    opacity: 0;
    position: absolute;
    top:-10000px;
    transition: opacity .5s, top 0s .5s;
}
```

In the JS editor (`view` menu, `JS scripts editor`), add this code somewhere:

``` JS
$(function() {
    setTimeout(function() {
        $('body').addClass('loaded');
    }, 0);
})
```

The JS code is used to avoid an animation on page load
