### ISSUE TITLE
Skill bar component

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/Silex#594]
I'm trying to create a new component based on [skill bars](https://codepen.io/tamak/pen/hzEer).

I copied a lot from the slideshow to give the ability to create new bar but have still some problems.

### Could not render the template at first run

When adding the component to the stage, I've got this error:
```
could not render the template TypeError: ejs:1
 >> 1| <% for(var bar of bars) { %>
    2| <div class="skillbar clearfix " data-percent="<% bar.percentage %>%">
    3|   <div class="skillbar-title" style="background: <%= bar.labelColor %>;"><span><%= bar.label %></span></div>
    4|   <div class="skillbar-bar" style="background: <%= bar.background %>;"></div>

bars is undefined
```
<details>
  <summary>Stacktrace</summary>

```
Stack trace:
anonymous@http://localhost:6805/libs/prodotype/prodotype.js line 44071 > Function:7:1
[1]</Template.prototype.compile/returnedFn@http://localhost:6805/libs/prodotype/prodotype.js:44071:7495
[1]</exports.render@http://localhost:6805/libs/prodotype/prodotype.js:44071:4251
doRender@http://localhost:6805/libs/prodotype/prodotype.js:43936:17
render/</<@http://localhost:6805/libs/prodotype/prodotype.js:43925:13
 Object { bars: undefined, uid: "1493816374608_948" } 
<% for(var bar of bars) { %>
<div class="skillbar clearfix " data-percent="<% bar.percentage %>%">
  <div class="skillbar-title" style="background: <%= bar.labelColor %>;"><span><%= bar.label %></span></div>
  <div class="skillbar-bar" style="background: <%= bar.background %>;"></div>
  <div class="skill-bar-percent"><%= bar.value %></div>
</div>
<% } %>
<style type="text/css">
.skillbar {
	position:relative;
	display:block;
	margin-bottom:15px;
	width:100%;
	background:#eee;
	height:35px;
	border-radius:3px;
	-moz-border-radius:3px;
	-webkit-border-radius:3px;
	-webkit-transition:0.4s linear;
	-moz-transition:0.4s linear;
	-ms-transition:0.4s linear;
	-o-transition:0.4s linear;
	transition:0.4s linear;
	-webkit-transition-property:width, background-color;
	-moz-transition-property:width, background-color;
	-ms-transition-property:width, background-color;
	-o-transition-property:width, background-color;
	transition-property:width, background-color;
}

.skillbar-title {
	position:absolute;
	top:0;
	left:0;
width:110px;
	font-weight:bold;
	font-size:13px;
	color:#ffffff;
	background:#6adcfa;
	-webkit-border-top-left-radius:3px;
	-webkit-border-bottom-left-radius:4px;
	-moz-border-radius-topleft:3px;
	-moz-border-radius-bottomleft:3px;
	border-top-left-radius:3px;
	border-bottom-left-radius:3px;
}

.skillbar-title span {
	display:block;
	background:rgba(0, 0, 0, 0.1);
	padding:0 20px;
	height:35px;
	line-height:35px;
	-webkit-border-top-left-radius:3px;
	-webkit-border-bottom-left-radius:3px;
	-moz-border-radius-topleft:3px;
	-moz-border-radius-bottomleft:3px;
	border-top-left-radius:3px;
	border-bottom-left-radius:3px;
}

.skillbar-bar {
	height:35px;
	width:0px;
	background:#6adcfa;
	border-radius:3px;
	-moz-border-radius:3px;
	-webkit-border-radius:3px;
}

.skill-bar-percent {
  position:absolute;
  right:10px;
  top:0;
  font-size:11px;
  height:35px;
  line-height:35px;
  color:#ffffff;
  color:rgba(0, 0, 0, 0.4);
}
</style>
<script type="text/javascript">
$('.skillbar').each(function(){
  $(this).find('.skillbar-bar').animate({
    width:$(this).attr('data-percent')
  },6000);
});
</script>
```

</details>

I think this is the reason why my default value are not displayed until I edit them.

### Field number not taken into account

All of my fields works pretty well but I don't understand why my `percentage` filed is not inserted in the template. Here's my YAML:
```yaml
---
name: Skill bars
description: 'Represent a set of skills as progress bars.'
doc: https://github.com/silexlabs/Silex/wiki
category: Utils
tags:
- skill
- progress
- bar
isPrivate: false
baseElement: html
faIconClass: fa-tasks
initialCss:
  height: 400px
  width: 400px
  background-color: 'transparent'
props:
- name: bars
  description: Bars and labels
  type:
    - name: label
      type: string
      description: Label of the bar
      default: 'Skill #1'
    - name: percentage
      type: number
      description: Filled percentage of the bar
      default: 50
    - name: value
      type: string
      description: Value written in the bar
      default: Good
    - name: background
      type: color
      description: Background of the bar
    - name: labelColor
      type: color
      description: Background of the label
```
Did I missed something?

### Warning when picking a color

Maybe that's nothing but the first time I pick a color I get:
```
"Warning: ColorEditor is changing an uncontrolled input of type color to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components"
```
