### ISSUE TITLE
Mobile Hamburger: Hide pages?

### ISSUE THREAD

**Issue by Tyrael84** [silexlabs/Silex#651]
Is it possible to pick and choose which pages are displayed in the 'hamburger' menu on the mobile version of the site. I would assume it would involve some sort of JS or CSS.

**Comment by lexoyo** [comment]
Hello @Tyrael84 
For now this will require CSS, but we should make it easy in the future
Please add this CSS code in the "CSS style editor", but replace `***page name***` by the page name (e.g. `.page-mypagename {`
```css
#page-***page name*** {
  display: none;
}
```

**Comment by lexoyo** [comment]
Hello @Tyrael84 
For now this will require CSS, but we should make it easy in the future
Please add this CSS code in the "CSS style editor", but replace `***page name***` by the page name (e.g. `.page-mypagename {`
```css
#page-***page name*** {
  display: none;
}
```

**Comment by lexoyo** [comment]
I tried on the "food and drink" template, and I could hide the "team" page from the mobile menu with this css code:
```css
#page-team {
  display: none;
}
```
