### ISSUE TITLE
Vertical Column Widget

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#686]
## About this widget

This widget is like a section element but it will be vertical and accross all sections:

![screenshot from 2018-02-10 16-37-53](https://user-images.githubusercontent.com/715377/36063730-c86135f0-0e80-11e8-9140-7cfefc6a9013.png)

Note: someone should make a component out of this widget so that it will appear in the "+" menu of SIlex, let me know if you want to know how to do this

(private message: special dédicace à @tariqbenezza)

## Setup

Open the CSS editor and add this code anywhere
```
/* ********************* */
/* Vertical Column widget */
/* ********************* */
.container-element.editable-style.section-element {
    display: flex;
    margin-right: 260px;
    /* 250+10 (10 is the margin of the vertical section in silex editor */
}

.silex-runtime .editable-style.section-element {
    display: flex;
    margin-right: 250px;
}

.vertical-section.editable-style.container-element,
.vertical-section.editable-style.section-element {
    float: right;
    width: 250px;
    min-width: 250px;
    margin-right: 0;
    padding: 0;
}
/* ********************* */
```
## Create a vertical culumn

[Add a **section** to the stage as explained in the docs](https://github.com/silexlabs/Silex/wiki/Editor-UI#elements-1), set its class name to `vertical-section` like this:

![screenshot from 2018-02-10 16-33-37](https://user-images.githubusercontent.com/715377/36063734-d9c18d68-0e80-11e8-8841-e973b78705e6.png)

Use the up/down arrows and move the section to the top:

![screenshot from 2017-05-15 23-07-40](https://cloud.githubusercontent.com/assets/715377/26079516/5438cd42-39c3-11e7-88b0-4ef998b5e6fc.png)

## Add content to the vertical column

You can add elements to the column like any other element, this should look like this

![screenshot from 2018-02-10 16-35-34](https://user-images.githubusercontent.com/715377/36063694-755a8da2-0e80-11e8-8584-50447ac4b931.png)

**Comment by lexoyo** [comment]
I should probably make it possible for the column to stick to the side of the section also, not only to the side of the window as it is for now

**Comment by lexoyo** [comment]
I did this another way for a website recently, using css grid
```css
@media (min-width:481px) {
    body {
        display: grid;
        grid-template-columns: 300px 1fr 300px;
        min-height: 100vh;
    }

    body > div {
        width: unset !important;
        height: unset !important;
    }

    body > .col1 {
        grid-column: 1;
    }

    body > .col2 {
        grid-column: 2;
    }

    body > .col3 {
        grid-column: 3;
    }

    body > .section-element {
        grid-column: 2;
        grid-row: 1;
    }
 }
```
