### ISSUE TITLE
The stage should be an iframe

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#80]
When you change the CSS of a website, it may interfere with Silex UI. For example

``` css
*{
    display: none;
}
```

This happens also when you set the position of an element to static.
